### ISSUE TITLE
Elevated rail not considered when collision checking

### ISSUE THREAD

**Issue by katepolak** [voxeltycoon/bug-tracker#1]
Part of rail that change the elevation don't seem to be considered when checking for a valid building spot. Doesn't matter if I build the elevation first or the flat one first, it works either way. Works with both curved and straight rails.

Both segments are still fully functional.

![image](https://user-images.githubusercontent.com/11616898/56514368-5f6a8800-6535-11e9-81eb-06d5401ca148.png)
![image](https://user-images.githubusercontent.com/11616898/56514391-6d200d80-6535-11e9-9bd3-e2d181410aab.png)
![image](https://user-images.githubusercontent.com/11616898/56514409-75784880-6535-11e9-9e3b-bd6ea5f9462e.png)
![image](https://user-images.githubusercontent.com/11616898/56514412-790bcf80-6535-11e9-85ec-1891ee6c7525.png)
![image](https://user-images.githubusercontent.com/11616898/56514462-99d42500-6535-11e9-94e3-e82e8c7546a4.png)
![image](https://user-images.githubusercontent.com/11616898/56514700-4c0bec80-6536-11e9-99c9-0ac1e2f90418.png)

**Comment by andrewpey** [comment]
Fixed in 0.64.
