### ISSUE TITLE
Paused game - sound continues

### ISSUE THREAD

**Issue by goldenarrow** [voxeltycoon/bug-tracker#104]
**Describe the bug**
Pause the game on a steam engine and the train 'continues' to finish the acceleration, then continues with the same sound loop. Unpausing the game then leads to two steam engine sounds, but pausing again will drop back to one. 

The sound stays at the same volume where ever you move.

**Steps to reproduce**
Place steam engine, set it going, pause game.

**Build version**
0.72 2019-07-04 Pre-Alpha

**Platform**
Windows 10

**Reproducibility**
Every time.

**Comment by katepolak** [comment]
Fixed in 0.74
