### ISSUE TITLE
Amount of resources in the train car

### ISSUE THREAD

**Issue by DocKirk** [voxeltycoon/bug-tracker#106]
**Describe the bug**
A clear and concise description of what the bug is. If applicable, add screenshots or video to help explain your problem.
![Screenshot_156](https://user-images.githubusercontent.com/23107204/60743421-2f4e5500-9f7a-11e9-8c96-a9637b3d5cc9.jpg)
![Screenshot_157](https://user-images.githubusercontent.com/23107204/60743422-2f4e5500-9f7a-11e9-8750-14e015120997.jpg)

**Steps to reproduce**
Steps to reproduce the behavior.

**Build version**
Version information can be found at the bottom of the settings window.

**Platform**
OS name and version.

**Reproducibility**
How often an issue reproduces: every time, often, rare, once.

**Comment by katepolak** [comment]
Please update the description to say what the actual issue is, from what you sent I don't see any.

**Comment by victorleblais** [comment]
What I think @DocKirk is saying is that there's a balancing issue / "logic issue":

- Truck trailer is 9m long and contains 17 units.
- Train railcar is 15 meters long and contains 15 units.
