### ISSUE TITLE
Add visualisation for conveyor direction

### ISSUE THREAD

**Issue by aLegoz** [voxeltycoon/bug-tracker#11]
If your game on pause, you don't understand conveyor directrion. 
I think that you need add visualisation for conveyor direction. For example: arrows in conveyors build mode will look well. 
![](https://i.imgur.com/r1zNDcy.png)
![](https://i.imgur.com/Or6juLF.png)

**Comment by katepolak** [comment]
Changing the graphic just for the build view would be quite counter intuitive I would say, there are two options that I would say are better.

- Change to a arrow based texture for the whole time
- When the user hovers on top of a conveyor segment, display the direction on top of it as a "arrow dotted line", example bellow


----------
![image](https://user-images.githubusercontent.com/11616898/56601914-99eb2800-65fc-11e9-842b-63ba7b306ae7.png)
(custom cursor added manually as screenshots do not include it)
Green arrows indicate the segment the user is hovering above, orange ones would display above all segments that are connected to it.

**Comment by voxeltycoon** [comment]
Changed texture to arrow-shaped (in both build and normal mode) in 0.52.

@polak-jan feel free to create separate issue from your comment if it's still actual.
![image](https://user-images.githubusercontent.com/34013054/56699809-c8056080-66ff-11e9-8635-66306fa39421.png)
