### ISSUE TITLE
Freight Terminal Detaching from Base

### ISSUE THREAD

**Issue by MountainDan** [voxeltycoon/bug-tracker#114]
**Describe the bug**
Freight Terminal became detached from its base when I tried to place in the town, The Terminal became locked to the cursor, this resulted in all other build items becoming unusable. top level menus were still clickable but secondary menus where locked out.

**Steps to reproduce**
I already had 2 freight terminals in the town so maybe that is the cause?

**Build version**
V0.72

**Platform**
Windows 10 home 64bit

**Reproducibility**
this is the first time I have experienced this bug

![Screenshot (72)](https://user-images.githubusercontent.com/13538091/61055738-7aaeaa80-a435-11e9-8c4c-edbb645491a5.png)

[Player log.zip](https://github.com/voxeltycoon/bug-tracker/files/3382275/Player.log.zip)

**Comment by andrewpey** [comment]
I believe it was fixed long ago.
