### ISSUE TITLE
Train edit window is not closed after selling the train

### ISSUE THREAD

**Issue by mayorandrew** [voxeltycoon/bug-tracker#117]
**Describe the bug**
If you sell the train while reconfiguring it, the configuration window will not close automatically. This may potentially lead to other bugs if you do somethings in this window (I haven't tested that thoroughly). I think it would be simplier to just close this window automatically

**Steps to reproduce**
Open depot, buy train, open train reconfiguration window, sell train

**Build version**
v0.73 russian

**Platform**
Windows 10 build 1809

**Reproducibility**
Always

**Comment by katepolak** [comment]
Likely related to #76 and #24

**Comment by anthonycl** [comment]
Your train exists not.  Hmmmmmm.

**Comment by voxeltycoon** [comment]
Fixed in 0.75
