### ISSUE TITLE
Game fails to load asses base/cs.strings

### ISSUE THREAD

**Issue by Martin819** [voxeltycoon/bug-tracker#119]
**Describe the bug**
The game fails to load an asset "base/cs.strings" during the startup. After clicking on confirmation "Go back" button, the game closes. (See attached screenshot)

Error message trancription:

```
Invalid character after parsing property
name. Expected ':' but got: ,. Path
'items.base/copied_to_clipboard', line
65, position 58.
```

**Steps to reproduce**
Just start the game via Itch.io launcher.

**Build version**
Itch launcher says it's the current latest version, which should be 0.74. Not able to verify tho, because I'm not able to get to the menu.
Is there a way to find out version another way?

**Platform**
Windows 10 x64 via Itch launcher

**Reproducibility**
Every time

![vt_error_cssttrings](https://user-images.githubusercontent.com/24304336/61558593-cd0c4e80-aa67-11e9-8620-f839a1c24d62.png)

**Comment by katepolak** [comment]
This is an issue with the Itch launcher updater we have encountered already unfortunately. I would recommend reinstalling your game which should fix it.

**Comment by Martin819** [comment]
I can confirm that after doing Manage -> Switch to another version -> version 0.74 in Itch launcher, it reinstalled the game (I suppose) and it's working just fine now. So I guess we can close this now. Thanks for the help.

**Comment by katepolak** [comment]
Closing than. Glad it got solved.
