### ISSUE TITLE
Bulldozing price inconsistent

### ISSUE THREAD

**Issue by katepolak** [voxeltycoon/bug-tracker#12]
### Platform
Windows

### Version
Both 0.50 and 0.51

### Details
Bulldozing prices are quite inconsistent, it's the same with both rails and roads.

Bulldozing price is always free for the first segment, and when you remove a single piece all the pieces around it are updated.

There is also a difference between an endpoint (buffer stop/rounded road) and a single piece (215 and 150 respectively)

Related to #7 but more widespread.

### Videos
Rails: https://streamable.com/k1cn0
Roads: https://streamable.com/9bklu

**Comment by katepolak** [comment]
Devs commented that there shouldn't be any price at all, just putting it here to make sure it doesn't get lost.

**Comment by andrewpey** [comment]
Fixed in 0.56.
