### ISSUE TITLE
Truck says it is Lost, even with valid path

### ISSUE THREAD

**Issue by juffanoodle** [voxeltycoon/bug-tracker#121]
**Describe the bug**
Truck declares it is lost on a long route, despite a valid path existing. If I add an intermediate destination, the truck routes successfully to all three stops.

**Steps to reproduce**
See save file https://drive.google.com/file/d/1QYUppkJk7VUzuR9QOnhVoogutvoKal-5/view?usp=sharing

Vehicles 144, 145 and 146 can't route between the terminal called Stone Brick Depot near Custer, to Ukiah Halt in Ukiah - they declare they are lost. If I add a 'Go To' order to the terminal Halfway House, both legs succeed. Deleting the Go To order when the truck has just left Stone Brick Depot causes a Lost notification again.

Routing from Ukiah Halt to Stone Brick Depot also succeeds.

**Build version**
0.74 2019-07-19 ITCH PRE-ALPHA

**Platform**
Windows 10

**Reproducibility**
Reproducible in this save file, haven't seen it elsewhere.

**Comment by voxeltycoon** [comment]
Fixed in 0.75
