### ISSUE TITLE
Keyboard Buffer Fills with XBXBXBXBXBXBX, etc

### ISSUE THREAD

**Issue by MiserableGamer** [voxeltycoon/bug-tracker#123]
Whilst playing the game, the laying of rails breaks and you cannot create curves, just straight sections of track.  When exiting the game, the keyboard buffer is constantly filling with XBXBXBXBXBX rendering the OS inoperable and requires restart.  Once restarted, the saved game works fine again.

**Comment by victorleblais** [comment]
Hi !
It would be great if you provided a bit more details:
- What version of the game are you using (Can be seen in the Settings menu)
- What OS and OS version are you using?
- Is that issue happening all the time?
- How can we reproduce it?

**Comment by katepolak** [comment]
Thanks for the report. Could you please describe what happened more closely? What exactly did you do in game and what exactly did the issue was when you exited the game? I don't see a reason the game should be attempting to write characters for you, especially not when it isn't running.

**Comment by MiserableGamer** [comment]
It's happened about 3 to 4 times....when I've got the game paused and doing some track work, suddenly the game will only allow straight track, even when extending existing track. The buffer fill only happens with VT, nothing else. I don't think it's filling the buffer after exit, but more there is still stuff in the buffer, and if you pull up Windows search, it's filling the text box continually.

I'm not at the machine anymore today, but I think it's version 0.74 from Itch App, Windows 10 latest build. 

I can get more specific version details when I'm at my desk again tomorrow.

**Comment by katepolak** [comment]
I honestly can't think of a single reason this should be happening. Even looked through the code quickly and don't see one either.

I don't think anything can be done without having logs from this happening.
