### ISSUE TITLE
Voxel Tycoon mod listing allows mods with unconventional json files

### ISSUE THREAD

**Issue by GameBurrow** [voxeltycoon/bug-tracker#128]
**Describe the bug**
I've found a mod in Voxel Tycoon's mod list, that has broken `pack.json` file. This is the file:
```
{
    "Title" : "Mighty Griffin v2.0",
    "Description" : "Pack of Scania 5 generetion R-, P-, T-series.
    LQ version: pack contain trucks without overdetilization, so it will save your FPS at initial state.
    V1.0 (21.07.19): initial release.
    V2.0 (28.07.19): Fully reworked models. Added curtain and flatbed body types. Added semirtailers and HCT roadtrains.
    In next update: More body types for trucks and trailers, more semitrailers"
}
```
Most JSON parsers (what I've tried so far) by default fail to parse that file and that is because of the multiline string added to `Description` field. Json files should be validated before mod is allowed to be uploaded.

I stumbled upon this issue when I tried to make a small mod manager for myself.

Mod details:
```
  {
    "Author": "SpaceCossaX",
    "Updated": "2019-07-28T12:22:08.491Z",
    "Disabled": false,
    "Name": "scania_p_r_t_pack"
  },
```

**Steps to reproduce**
Download **Mighty Griffin v2.0** mod and try to parse the pack.json file outside of the game (for example online json parsers like http://json.parser.online.fr/)

**Build version**
![image](https://user-images.githubusercontent.com/4341091/62204276-930b4880-b395-11e9-87b3-1e56251475a3.png)

**Platform**
Windows 10 Pro x64

**Reproducibility**
N/A

**Comment by andrewpey** [comment]
Fixed in [0.84](https://voxeltycoon.xyz/changelog#0.84).
