### ISSUE TITLE
UI scale hides Message dates.

### ISSUE THREAD

**Issue by br3n065** [voxeltycoon/bug-tracker#129]
**Describe the bug**
The dates on messages disappear when using either 90% or 120% User interface scale.
The below image shows how it should look, at 100%, and what it actually looks like at 120%. 
![BUG_UIscale](https://user-images.githubusercontent.com/31400369/62273912-0f7b5580-b482-11e9-97cc-21a4ca37145d.png)

**Steps to reproduce**
Open Settings, and change 'UI scale' to either 90% or 120%.

**Build version**
0.74 2019-07-19 ITCH PRE-ALPHA

**Platform**
Arch Linux, 64-bit, 5.2.5-arch1

**Reproducibility**
Every time

**Comment by voxeltycoon** [comment]
Fixed in 0.75
