### ISSUE TITLE
Road bulldozing all over the place

### ISSUE THREAD

**Issue by katepolak** [voxeltycoon/bug-tracker#13]
#### Platform
Windows

#### Version
0.51

#### Details

The segments the bulldozer removes in it's default mode can overlap each other or even be comprised of multiple separate parts. I can't really find a way to replicate each of the cases, but it looks like the main issue is when there are very tight U turns and pretty much every time something weird happens.

#### Videos

https://streamable.com/lm1s1
https://streamable.com/yslvw

#### Screenshots

![image](https://cdn.discordapp.com/attachments/537669559302356994/570161818983727114/unknown.png)

**Comment by andrewpey** [comment]
Fixed in 0.64.
