### ISSUE TITLE
Terminal screen does not refresh when new vehicles added to route via garage clone

### ISSUE THREAD

**Issue by Mozleron** [voxeltycoon/bug-tracker#130]
**Describe the bug**
With a Terminal window open, cloning a vehicle belonging to the opened Terminal via the Garage clone button, the Terminal screen does not update.

**Steps to reproduce**
Open a Terminal window.
Open a Garage.
Click Clone button in Garage window.
Choose a vehicle that is currently reporting to opened Terminal.
Observe new vehicle in Garage screen.
Check it's route and note that it should be reporting to the opened Terminal.
Note that the Terminal vehicle list has not update.

-Terminal screen does update if tabs are switched or window is closed and reopened.

**Build version**
0.75

**Platform**
Windows 10

**Reproducibility**
every time.

**Comment by andrewpey** [comment]
Fixed.
