### ISSUE TITLE
When stations are all connected back and forth, Train does not turn around in place

### ISSUE THREAD

**Issue by sunaneko-1324** [voxeltycoon/bug-tracker#131]
**Describe the bug**
When stations are all connected back and forth, Train does not turn around in place.

**Steps to reproduce**
![linked](https://user-images.githubusercontent.com/17085696/62449831-0225da00-b7a6-11e9-9acc-eceb62ed72b1.jpg)
The route is a double line, connected in a circle.
The station (anniston) in the middle is accessible from both directions.

![goto](https://user-images.githubusercontent.com/17085696/62449836-05b96100-b7a6-11e9-8d75-1e7e0977363b.jpg)
when train is go to anniston to cranston, although it is fast for trains to turn around in place, but instead of turning around, that leave the station along the front connected circular route.

In almost all cases, the train did not turn around in place, when stations are all connected back and forth.

**Build version**
0.75 2019-08-02

**Platform**
windows 10 pro 1903

**Reproducibility**
always

**Comment by katepolak** [comment]
If I correctly understand what you mean than it's an intended behaviour. Trains will always try to avoid turning around, even if the detour would be way longer

**Comment by sunaneko-1324** [comment]
really?? I do not understand well.
if this is the intended function, it is very cumbersome.

**Comment by katepolak** [comment]
If a train find a way to the destination that doesn't involve turning around it will always chose it, even it is multiple times as long as if he turned around. As far as i know games like OpenTTD handle situations like this the same way.

But no matter what it certainly isn't a bug, if you want this behaviour changed you can post a suggestion about it on the suggestion tracker though.

**Comment by sunaneko-1324** [comment]
I understand what you mean. But openttd does not work this way.

In openttd, trains travel at the shortest distance unless you limit the path.

Since the settings allow the train to turn around in place, it should work as configured.

**Comment by andrewpey** [comment]
@polak-jan is right, this is currently is intended behavior. If you see how this behavior could be improved, feel free to open a suggestion here: https://github.com/voxeltycoon/suggestions/issues.

**Comment by katepolak** [comment]
Also just checked it in OTTD, it indeed works just like it does in Voxel Tycoon. Here is a screenshot from my phone: ![](https://i.imgur.com/BwYXTFF.jpg)

**Comment by sunaneko-1324** [comment]
![2019-08-06 (1)](https://user-images.githubusercontent.com/17085696/62488186-a20f5200-b7fe-11e9-975a-ad4c92ef76c3.png)

no, you need longer circle route. try it.

**Comment by sunaneko-1324** [comment]
![image](https://user-images.githubusercontent.com/17085696/62493961-51532580-b80d-11e9-86e3-4970bd8b1ab8.png)

And the example is wrong. Here is my configuration:

**Comment by victorleblais** [comment]
As of 0.76 release, you can now choose which behavior you want (turning around or continuing straight ahead) thanks to the new task available in the vehicle's orders.
