### ISSUE TITLE
"New messages" divider text disappears at 90% and 120% UI scale

### ISSUE THREAD

**Issue by drewtato** [voxeltycoon/bug-tracker#132]
**Describe the bug**

The text "NEW MESSAGES" that appears in the Messages dialog between old and new messages disappears when the UI scale is at 90% or 120%.

![image](https://user-images.githubusercontent.com/15526875/62492487-9894d400-b783-11e9-9925-513eed03ac05.png)

**Steps to reproduce**

* Set scale to 120%
* Wait for notification
* Open notification dialog

**Build version**

0.75 2019-08-02

**Platform**

Windows 10

**Reproducibility**

Every time.

**Comment by andrewpey** [comment]
Fixed in `0.76`
