### ISSUE TITLE
camera view not change when follow vehicle

### ISSUE THREAD

**Issue by sunaneko-1324** [voxeltycoon/bug-tracker#134]
**Describe the bug**
camera view not change when following vehicle.

**Steps to reproduce**
1. prepare the routed vehicle.
2. click the vehicle.
3. click follow vehicle.
4. click any destination in the window.

please refer to the video below to check the issue.
https://youtu.be/4qhgvXWOp4A

**Build version**
0.75

**Platform**
windows 10 pro

**Reproducibility**
every time

**Comment by andrewpey** [comment]
Fixed in `0.76`
