### ISSUE TITLE
Diagonal rails cannot be removed at the edge of an locked region

### ISSUE THREAD

**Issue by sunaneko-1324** [voxeltycoon/bug-tracker#136]
**Describe the bug**
Diagonal rails cannot be removed at the edge of an locked region

**Steps to reproduce**
1. place diagonal rails at locked region edge.
2. when remove rails - can not remove rails.
(popup shown 'Region disallows this.')

https://youtu.be/bIkWHZnatXY

**Build version**
0.75

**Platform**
windows 10 pro

**Reproducibility**
every time

**Comment by andrewpey** [comment]
Fixed.
