### ISSUE TITLE
when moving camera view, tooltip is disappered

### ISSUE THREAD

**Issue by sunaneko-1324** [voxeltycoon/bug-tracker#138]
**Describe the bug**
when moving camera view, tooltip is disappered

**Steps to reproduce**
1. click any laboratory.
2. click 'start new research'.
3. mouse over any items.
4. when tooltip shown, to moving camera view. - tooltip is disappered

https://youtu.be/F3cZS_-ysHE

**Build version**
0.75

**Platform**
windows 10 pro

**Reproducibility**
every time

**Comment by andrewpey** [comment]
This is intended behavior - tooltips are closing on any input.
