### ISSUE TITLE
Laboratories not renamed when language is changed

### ISSUE THREAD

**Issue by sunaneko-1324** [voxeltycoon/bug-tracker#139]
**Describe the bug**
Laboratory name issue when you change the game language

**Steps to reproduce**
1. start new game. (or load any game)
2. built laboratory.
3. name is 'laboratory 1'.
4. to change any game language.
5. built another laboratory.
6. when check laboratory name - 'laboratory 1' is created for the language you set.
(but you can't rename a lab in a game.)

https://youtu.be/aG5M9jo7kZw

**Build version**
0.75

**Platform**
windows 10 pro

**Reproducibility**
every time

**Comment by katepolak** [comment]
Even though you can't rename them their names are still store in the save game as is apparent from the behaviour described. I would consider this an intended behaviour as it allows the same logic to be used for storing all common attributes of buildings. If you would like this to behave differently than opening a suggestion is the beat option.
