### ISSUE TITLE
Conveyors can be build inside each other

### ISSUE THREAD

**Issue by katepolak** [voxeltycoon/bug-tracker#14]
#### Platform
Windows

#### Version
0.51

#### Details
Related to #4 but more wide spread. Might be better to post those images into comments here and close that one as it's too specific.

Conveyors can pretty easily be built inside each other, they end up working fine for the most part, but it produces some graphical glitches and bulldozing/rotating them can get pretty nasty.

Reproduction video included.

#### Videos

Reproduction: https://streamable.com/k6nxj
General look when the conveyor is in action + removing it: https://streamable.com/099uq
Rotation the conveyor: https://streamable.com/e2rdi

**Comment by andrewpey** [comment]
Fixed in 0.64.
