### ISSUE TITLE
Station window does not close with esc key

### ISSUE THREAD

**Issue by sunaneko-1324** [voxeltycoon/bug-tracker#141]
**Describe the bug**
Station window does not close with esc key

**Steps to reproduce**
1. prepare any station.
2. click the station.
3. build a warehouse with station window shown.
4. when esc key press - station window does not closed.
(If you press esc immediately without building the warehouse, the window will close.)

https://youtu.be/dCxkrQBVw-I

**Build version**
0.75

**Platform**
windows 10 pro

**Reproducibility**
every time

**Comment by katepolak** [comment]
This is because you don't have the window in focus anymore after performing another action. Not a bug.

**Comment by sunaneko-1324** [comment]
If so, the focus should be visible in the window.

**Comment by katepolak** [comment]
That's true, I will make a suggestion for that.
