### ISSUE TITLE
Launch/Start crash with missing citynames file report

### ISSUE THREAD

**Issue by Vaupell** [voxeltycoon/bug-tracker#143]
**Describe the bug**
Launching the game, crashes
![VoxelTycCrash](https://user-images.githubusercontent.com/2694539/63094213-043b2600-bf68-11e9-8154-0c4dda3949b3.PNG)

**Steps to reproduce**
no idea

**Build version**
Launched with latest version on itch

**Platform**
Win10

**Reproducibility**
every time,

**Comment by andrewpey** [comment]
Does it still reproduce?

**Comment by andrewpey** [comment]
No additional info was provided, closing.
