### ISSUE TITLE
InvalidOperationException thrown when enabling Station view, breaks UI

### ISSUE THREAD

**Issue by alesandroortiz** [voxeltycoon/bug-tracker#145]
**Describe the bug**
When loading particular save files and then enabling the Station data view, an exception is thrown repeatedly. Data views break and there's UI oddities which pretty much make the game unplayable after exception is thrown. Enabling all other views does not throw any exceptions.

Issue started in my "Oregon City44" (`x33rpb5opk`) save file, but "Oregon City43" (`18o3f7ksa4f`) save file is okay. All other save files after "Oregon City44" have same issue (my most recent is "Oregon City49").

I didn't have the issue when playing the map yesterday (loaded from "Oregon City43" or prior save file), and was able to continue playing and saving for hours. I only faced the issue when loading the same save files today (44-49 are affected.)

Attached save files were saved with version 0.76, but I think earlier save files of same map were created with 0.75. Not sure what changed between save files 43 and 44, but I've provided both save files in case it helps.

Sample logged exception below:

```
InvalidOperationException: Can't get vehicle type from location with no vehicles serviced.
  at VoxelTycoon.Tracks.VehicleStationLocationManager.GetServicedVehicleType (VoxelTycoon.Tracks.VehicleStationLocation location) [0x0003e] in <e6b4f316da03439ba6d7f67187eabb0b>:0 
  at VoxelTycoon.Game.UI.VehicleStationLocationIndicator.InvalidateContent () [0x00005] in <e6b4f316da03439ba6d7f67187eabb0b>:0 
  at VoxelTycoon.UI.Indicator.OnLateUpdate () [0x00139] in <e6b4f316da03439ba6d7f67187eabb0b>:0 
  at VoxelTycoon.UI.IndicatorManager.OnLateUpdate () [0x0003e] in <e6b4f316da03439ba6d7f67187eabb0b>:0 
  at VoxelTycoon.UpdateBehaviour.LateUpdate () [0x0000a] in <e6b4f316da03439ba6d7f67187eabb0b>:0 
 
(Filename: <e6b4f316da03439ba6d7f67187eabb0b> Line: 0)
```

**Steps to reproduce**
Method A:
1. Load "Oregon City44" (`x33rpb5opk`) save file.
2. Go to view menu on top left of screen.
3. Enable "Station" data view for regular view.

Method B:
1. Load "Oregon City44" (`x33rpb5opk`) save file.
2. Press alt key to enable alt view (which has "Station" data view enabled.)

Expected behavior:
No exception is thrown, station data is shown.

Observed behavior:
Exception is thrown repeatedly, even when game is paused. UI breaks affecting playability. Station data is not shown.

**Build version**
0.76 2019-08-15 Itch Pre-Alpha

**Platform**
Windows 10 OS Version 1809 (Build 17763.678)

**Reproducibility**
Every time when loading "Oregon City44" and subsequent saves I made on same map. Never with "Oregon City43".

**Attachments**
Player.log: [Player_x33rpb5opki_OregonCity44.log](https://github.com/voxeltycoon/bug-tracker/files/3514136/Player_x33rpb5opki_OregonCity44.log)
Oregon City44: [x33rpb5opki.zip](https://github.com/voxeltycoon/bug-tracker/files/3514139/x33rpb5opki.zip)
Oregon City43: [18o3f7ksa4f.zip](https://github.com/voxeltycoon/bug-tracker/files/3514140/18o3f7ksa4f.zip)

Let me know if you need more info or have trouble reproducing.

**Comment by andrewpey** [comment]
Do you remember if you done anything related to vehicle station rebuilding between City43 and City44? Like, removing a station?

If you have just removed a station without rebuilding, did you reassigned all the vehicles to another station before saving to City44?

**Comment by tjvr** [comment]
I've got this too -- I saw the bug report, but kept playing for a few hours -- and now that I try to load the world again, I realise it's made my world unplayable 😞 

```
InvalidOperationException: Can't get vehicle type from location with no vehicles serviced.
  at VoxelTycoon.Tracks.VehicleStationLocationManager.GetServicedVehicleType (VoxelTycoon.Tracks.VehicleStationLocation location) [0x0003e] in <e6b4f316da03439ba6d7f67187eabb0b>:0 
  at VoxelTycoon.Game.UI.VehicleStationLocationIndicator.InvalidateContent () [0x00005] in <e6b4f316da03439ba6d7f67187eabb0b>:0 
  at VoxelTycoon.UI.Indicator.OnLateUpdate () [0x00139] in <e6b4f316da03439ba6d7f67187eabb0b>:0 
  at VoxelTycoon.UI.IndicatorManager.OnLateUpdate () [0x0003e] in <e6b4f316da03439ba6d7f67187eabb0b>:0 
  at VoxelTycoon.UpdateBehaviour.LateUpdate () [0x0000a] in <e6b4f316da03439ba6d7f67187eabb0b>:0 
 
(Filename: <e6b4f316da03439ba6d7f67187eabb0b> Line: 0)
```

Here's my world, in case it helps at all!
[vxecw1dkcnk.zip](https://github.com/voxeltycoon/bug-tracker/files/3517348/vxecw1dkcnk.zip)

**Comment by andrewpey** [comment]
@tjvr thanks! The fix is in the works.

**Comment by andrewpey** [comment]
We've just uploaded the hotfix, version `0.76 2019-08-20`.

It should be ok now. Please let us know otherwise.

**Comment by alesandroortiz** [comment]
@andrewpey Thank you so much! All the affected game files now work.

Sorry I didn't get back to you earlier. I probably did replace stations first, then reassigned vehicles (if needed.) Can't confirm that's the case, though, since it was a while ago.

**Comment by tjvr** [comment]
Thanks, mine works again now too 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andrewpey** [comment]
@thephpjedi no problem, glad it's working now.
