### ISSUE TITLE
Right clicking a demand opens its UI

### ISSUE THREAD

**Issue by drewtato** [voxeltycoon/bug-tracker#148]
**Describe the bug**
For all other buildings, right clicking does nothing. This allows the player to haphazardly drag the map with right-click without having to worry about accidentally triggering anything. However, right clicking (including while dragging) a demand building/icon will open that demand's UI. This should only happen on left-click.

**Steps to reproduce**
Right click a demand

**Build version**
0.76 2019-08-30

**Platform**
Windows 10 1903

**Reproducibility**
Every time

**Comment by andrewpey** [comment]
Fixed in 0.77.
