### ISSUE TITLE
Editing a road segment will wreck any vehicles present on it

### ISSUE THREAD

**Issue by katepolak** [voxeltycoon/bug-tracker#15]
#### Platform
Windows

#### Version
0.51

#### Details
When you edit a road, by which I mean making an intersection out of it or adding a new exit to an existing intersection or turn, any vehicles that are present on that road will be wrecked.

This can only be observed when the game is sped up, at least I only managed to do it that way, and the actual issues is that you issue the build command and after it's checked if it's valid but before it is actually executed a vehicle can enter the edited segment and than get wrecked.

This isn't an issue with trains as rails can be edited when there is a train on top of them.

#### Video
https://streamable.com/o8mbs

**Comment by andrewpey** [comment]
Fixed in 0.64.

**Comment by katepolak** [comment]
Occurred in 0.71 again. Looks like it's under the same circumstances.

Reported by Skylark on Discord.

![](https://cdn.discordapp.com/attachments/594183435887837204/594251254549446666/unknown.png)

**Comment by katepolak** [comment]
Actually, turns out this is a separate issue. This was caused by the vehicle entering the segment after the checks occurred due to the game being sped up, #108 is caused by the checks simply not happening at all. Closing again.
