### ISSUE TITLE
Error popped up in the game

### ISSUE THREAD

**Issue by FirstGeekDanny** [voxeltycoon/bug-tracker#154]
**Describe the bug**
I haven't seen or noticed anything wrong, the game just popped up with a cute bug icon in the corner.

**Steps to reproduce**
Just play the game, popped up on it's own.

**Build version**
0.79 12-28-2019 ITCH PRE-ALPHA

**Platform**
Windows 10 x64 1909

**Reproducibility**
Seems to have just occurred once.

[Player.log](https://github.com/voxeltycoon/bug-tracker/files/4055202/Player.log)
![Voxel Tycoon Error](https://user-images.githubusercontent.com/30553736/72283259-102a3180-3647-11ea-99a2-36a621588ba4.jpg)

**Comment by andrewpey** [comment]
Fixed in 0.79 hotfix.
