### ISSUE TITLE
kW showing despite hp being selected

### ISSUE THREAD

**Issue by goldenarrow** [voxeltycoon/bug-tracker#155]
Version 0.79 2020-01-28 Itch Pre-Alpha

Although hp is selected and the power output being shown as hp, the maximum output is showing in kW:

![image](https://user-images.githubusercontent.com/38834964/74604025-cb644100-50b1-11ea-95f8-b688c5368160.png)

![image](https://media.discordapp.net/attachments/594183435887837204/678567857843470346/unknown.png?width=960&height=441)

**Comment by andrewpey** [comment]
Fixed in [0.85](https://voxeltycoon.xyz/changelog#0.85).
