### ISSUE TITLE
Modification can be updated twice

### ISSUE THREAD

**Issue by ndelta0** [voxeltycoon/bug-tracker#156]
**Describe the bug**
Mod in Mod Browser can be updated twice - first in "installed" tab and then second in "gallery" tab. Yes, it's not game-breaking but just a heads up.

**Steps to reproduce**
1. Have any installed mod updated by author.
2. Go to the Mod Browser
3. Update the mod on "installed" tab
4. Update again in "gallery" tab

**Build version**
0.79 2020-01-28 ITCH PRE-ALPHA

**Platform**
OS name and version.

**Reproducibility**
Probably every time, no way to test that.

**Comment by andrewpey** [comment]
Mod Browser was reworked in `0.83`.
