### ISSUE TITLE
when change which item to store, the former items disappears

### ISSUE THREAD

**Issue by kristofeI** [voxeltycoon/bug-tracker#157]
**Describe the bug**
You can tell to storage which item you want to store. Then you store it. Then you change because you want to store something else. Where is the previous stock? It vanished.

As above

**Build version**
0.79 2020-01-28 ITCH PRE-ALPHA

**Platform**
Ubuntu 19.04.

**Reproducibility**
Every time.

**Comment by victorleblais** [comment]
I think this is just the intended behavior for now.
