### ISSUE TITLE
Cannot delete a savegame from the Save window

### ISSUE THREAD

**Issue by victorleblais** [voxeltycoon/bug-tracker#158]
**Describe the bug**
It looks like you cannot remove/erase a savegame from the save window.

**Steps to reproduce**
- Create a game and save it as "Test"
- Create another game, try to save it as "Test" (by typing the name, not clicking on the existing save)
- A popup says "A save with this name already exists"
- Click "Delete" on the existing "Test" save
- Try to save again as "Test", you get the same popup
- Close the window (without saving)
- Re-open the save window
- The previous "Test" save is still here --> not normal !

**Build version**
0.79 2020-01-28 ITCH PRE-ALPHA

**Platform**
Windows 10 Pro N 64-bit
Intel i7-8700k, 6 cores, 12 threads at 4.4Ghz
32GB of RAM, DDR4, 3466Mhz
GTX 1080Ti

**Reproducibility**
100% of the time.

**Comment by andrewpey** [comment]
Fixed in the upcoming 0.80.
