### ISSUE TITLE
Conveyor placement near devices is sketchy

### ISSUE THREAD

**Issue by katepolak** [voxeltycoon/bug-tracker#16]
**Describe the bug**
Under the correct circumstances, which is when there is a 1 block wide gap between a conveyor and a device, when you try to place that one missing conveyor it freaks out connecting to non existing places, the behavior changes depending on what part of the voxel underneath you point at.

Probably related to #10.

Video showing the bug can be found bellow.

**Steps to reproduce**
Steps provided as a video bellow
https://streamable.com/sso6u

**Build version**
0.51 2019-04-23 PRE-ALPHA

**Platform**
Windows 10 Enterprise 1903
(legal Enterprise copy actually)

**Reproducibility**
Every time

**Comment by andrewpey** [comment]
Fixed in 0.64.
