### ISSUE TITLE
few bugs

### ISSUE THREAD

**Issue by JOSHUASAMPSON** [voxeltycoon/bug-tracker#160]
the bug is I guess a bug its a loading issues when I play it takes about few minutes to load into the game and after buy each region takes a long time for it to be purchased

load into game, after purchasing regions, loading game
 

pre alpha 0.80

pre alpha 0.80 windows 10

happens every single time but gets worse as you play

**Comment by andrewpey** [comment]
Exploring regions and loading worlds will always take time, this can't be done immediately.

Also, please use the issue template and choose more informative names for issues next time.
