### ISSUE TITLE
long running game crash

### ISSUE THREAD

**Issue by JOSHUASAMPSON** [voxeltycoon/bug-tracker#161]
game just crashes after a few hours it starts to load then never ends just crashes
   

play for a few hours and at some point will crash the game

Pre Alpha 0.80

*windows 10 alpha 0.80

happens so far every time ive played the game 11+ times

**Comment by andrewpey** [comment]
Please attach the log file after a crash happens (located here: `%appdata%/../LocalLow/VoxelTycoon/VoxelTycoon/Player.log`).

**Comment by andrewpey** [comment]
No info was provided, closing.

**Comment by JOSHUASAMPSON** [comment]
i havent bee on or in the game for awhile
