### ISSUE TITLE
lagging

### ISSUE THREAD

**Issue by JOSHUASAMPSON** [voxeltycoon/bug-tracker#162]
when I first bought the game and ever since then its been really lagging slowing down and loading for no reason.

just start game and laggs

pre alpha 0.80

windows 10 

all the time

**Comment by andrewpey** [comment]
Please attach the log file (located here: `%appdata%/../LocalLow/VoxelTycoon/VoxelTycoon/Player.log`).

**Comment by victorleblais** [comment]
It would also be useful to provide your computer's specification such as the model of processor (CPU), quantity and frequency of your RAM, model of your graphics card (GPU).

You should be able to get that basic information inside the Task Manager in the various tabs.

**Comment by andrewpey** [comment]
No additional info was provided, closing it by now.
