### ISSUE TITLE
artifacts on screen, menu icons disappear

### ISSUE THREAD

**Issue by straderfr** [voxeltycoon/bug-tracker#163]
**Describe the bug**

the first instance was following me having been repeatedly reloading the same  auto-save. I captured the issue on video, but did not know to get logs at the time.   no other data gathered.
https://youtu.be/dY2bsxL0P98

Issue came up again today (though the artifacts were a little different, including a blue triangle that covered appx 1/6- 1/4 of the screen)
 I had been loading several new games to find a seed I wanted to play, but had not yet begun to place anything when it began,  it lasted a while while i was setting up utilities to track memory, cpu, gpu use and temps, but when i was ready to record the artifacts were no longer showing up.

Ram was appx 3GB
CPU was being maxed with 60% from Voxel Tycoon
CPU/GPU/Memory Temps were in normal range
GPU was fluctuating between 10-70% use

Log file was 2.13 GB , containing 30,711,162 Lines of text.

The following lines account for the majority of the log file:

d3d11: failed to lock buffer 000002AB007282D8 of size 54560 [0x8007000E].
d3d11: failed to lock buffer 000002AB00722298 of size 4092 [0x8007000E].
d3d11: failed to lock buffer 000002AB00727A98 of size 12160 [0x8007000E].
d3d11: failed to lock buffer 000002AB00725418 of size 912 [0x8007000E].
d3d11: failed to lock buffer 000002AA6F59FFD8 of size 647159 [0x8007000E].
d3d11: failed to lock buffer 000002AA7B0CA1D8 of size 56815 [0x8007000E].
d3d11: failed to lock buffer 000002AAFFE637D8 of size 54560 [0x8007000E].
d3d11: failed to lock buffer 000002AAFFE616D8 of size 4092 [0x8007000E].
d3d11: failed to lock buffer 000002AAFFE63A98 of size 12160 [0x8007000E].
d3d11: failed to lock buffer 000002AAFFE5F318 of size 912 [0x8007000E].

Removing all instances of those errors using find and replace brings the total size from 2.13 GB to 941 KB, and the line count from 30,711,162 down to 19,364

github will not allow me to upload the full file due to its size, but it can be provided if you can direct me as to how to send it. meanwhile I did include the copy with those lines removed.

[Player.log](https://github.com/voxeltycoon/bug-tracker/files/4479005/Player.log)

**Steps to reproduce**
May be related to reloading the maps in rapid succession.

**Build version**
0.80.1.132307485299160380 ITCH PRE-ALPHA

**Platform**
Windows 10 64bit

**Reproducibility**
Has occurred twice to my knowledge

**Comment by victorleblais** [comment]
I'm not an expert, but these kinds of error sounds like the game was running out of video memory (VRAM), which is weird since you have an RX570 with 8GB of VRAM....

**Comment by andrewpey** [comment]
Looks like a video driver issue, not sure what we can do here.
