### ISSUE TITLE
macOS High Sierra 10.13.6 hangs on "loading..." screen

### ISSUE THREAD

**Issue by exp131** [voxeltycoon/bug-tracker#165]
Lastest version 0.81, runs normally, shows "Made with Unity" screen, and then shows the game logo and "Loading..." on the bottom of the screen, and nothing happens then (I wait about 30 minutes). It can be closed from the dock without a freeze.

**Comment by andrewpey** [comment]
Please try to run it via Itch App.

**Comment by exp131** [comment]
Yes, it works that way. Thanks
