### ISSUE TITLE
Black voxels in a locked region

### ISSUE THREAD

**Issue by YohDeadfall** [voxeltycoon/bug-tracker#167]
In one closed region some voxels are black. They constantly appear at the same places and do not disappear after the game reload.

![screenshot](https://user-images.githubusercontent.com/10694013/82148356-4e856680-985c-11ea-8bd6-27a6a6c848bf.png)

Game version: 0.82.1.132337412208497552

GPU: NVIDIA GeForce GTX 680
Driver version: 26.21.14.3200

**Comment by andrewpey** [comment]
Is this save from before 0.72? There a new biome was added in 0.72, causing worlds created before that in some cases could have such artifacts when exploring new regions.

**Comment by YohDeadfall** [comment]
Probably yes. Is there any way to fix an issue even if it's a manual solution requiring some fun with raw data?

**Comment by andrewpey** [comment]
I don't think this is possible, unfortunately.

The only possible workaround I can imagine is to remove the new biome from the game folder, then load the old version of save game (before corruption). But, obviously, it will require you to delete biome with every update, and you can't have it in new worlds.
