### ISSUE TITLE
Make game version copyable

### ISSUE THREAD

**Issue by YohDeadfall** [voxeltycoon/bug-tracker#168]
In the Settings dialog there is a game version which is required to post an issue, but here is a problem. It's very long and non-selectable.

### Proposal

At least the version should be selectable, so it can be copied and inserted into a ticket. Maybe it makes sense to copy it on click like this happens in some applications. In the last case there should be a tooltip or a notification that the version was copied to the clipboard.

Game version: 0.82.1.132337412208497552

**Comment by andrewpey** [comment]
Done in [0.84](https://voxeltycoon.xyz/changelog#0.84).
