### ISSUE TITLE
Created Mods can be installed over an unpublished version

### ISSUE THREAD

**Issue by goldenarrow** [voxeltycoon/bug-tracker#169]
In the current mod browser, your created mods are at the top (![image](https://user-images.githubusercontent.com/38834964/82932502-71142f80-9f80-11ea-8aae-2383f6819ae0.png)), with other user created mods below (as well as uninstalled versions of your own mods). (![image](https://user-images.githubusercontent.com/38834964/82933865-85f1c280-9f82-11ea-8d73-2792768ae607.png))

If you click on one of the your own uninstalled mods, it installs it over your unpublished mod, but a warning message pops up to say that a folder of that name already exists.

**Steps to reproduce it**
Have an uploaded mod. Install it. Find that you can no longer update your own mod, unless you edit packs.json 

**Build version**
v0.83

**Platform**
N/A 

**Reproducibility**
Every time

**Comment by andrewpey** [comment]
Thanks, will be fixed in the next update.

**Comment by andrewpey** [comment]
Fixed in [0.84](https://voxeltycoon.xyz/changelog#0.84).
