### ISSUE TITLE
Cities build invalid or illogical road formations

### ISSUE THREAD

**Issue by katepolak** [voxeltycoon/bug-tracker#17]
**Describe the bug**
Cities sometimes try to build roads where they can't, and they ignore the fact the build fails.

EDIT:
All cases I have seen so far have been either that the city tried to build a road connecting to a freight station but since that can only be on straights it doesn't succeed, or the same thing with sloped roads. I don't think it tries to build roads coming from the slopes or stations but rather connect existing roads to them for some reason.

![image](https://cdn.discordapp.com/attachments/537669559302356994/570218562921431060/unknown.png)
![image](https://user-images.githubusercontent.com/11616898/56584364-ebcf8600-65db-11e9-818a-dc826e9be83d.png)

**Steps to reproduce**
Wait for the town to grow, I guess 🤷‍♂️ Or use the cheat to force it, can be easily forced to build into desired places by building a rail "cage" around the city.

**Build version**
0.51 2019-04-23 PRE-ALPHA

Further confirmed occurrences:
- 0.58 2019-05-26

**Platform**
Windows 10 Enterprise 1903

**Reproducibility**
EDIT:
Very common
(previously said `rare` which was my assumption, but it was wrong as I simply wasn't looking hard enough, after a quick look this happens a lot even in small towns)

**Comment by goldenarrow** [comment]
I'd add that it isn't that rare. anywhere there is a road terminal or a gradient change in a town, these seem to form.

**Comment by goldenarrow** [comment]
In the latest release (0.58 2019-05-26), I found this:
![image](https://user-images.githubusercontent.com/38834964/58429259-3f326980-809d-11e9-852c-d8e2b42a279b.png)

**Comment by katepolak** [comment]
Yes, it's pretty common. I just haven't noticed it many times before making the issue. @andrewpey should I update the description or do you want the original posts to be left untouched?

**Comment by andrewpey** [comment]
@polak-jan I think it's a nice idea to update issues if you feel information there can be refined.

**Comment by Phelzier** [comment]
Hi guys,

I see this is still open, adding feedback anyway :)

![image](https://user-images.githubusercontent.com/22050004/60356227-5fb95080-99c8-11e9-8946-85c2f1d5c456.png)

**Comment by katepolak** [comment]
Fixed in 0.74.
