### ISSUE TITLE
Game does not start on MacOS

### ISSUE THREAD

**Issue by George-Krause** [voxeltycoon/bug-tracker#172]
**Describe the bug**
My game does not start. I double-click on VoxelTycoon.app and start the game. The black loading screen appears and lasts forever. In the lower area of the display "loading..." will be appear.

**Steps to reproduce**
1. Just start the game

**Build version**
0.84.1

**Platform**
MAC OSX Catalina (10.15.5)

**Reproducibility**
everytime

**Comment by andrewpey** [comment]
Please try to run the game via Itch App: http://itch.io/app.

If you weren't registered when bought the game, you should link it to your Itch account first: https://itch.io/docs/buying/already-bought.

**Comment by George-Krause** [comment]
I tried it with the Itch App Launcher and it works fine. Thank you.
