### ISSUE TITLE
Radius highlighting not working correctly

### ISSUE THREAD

**Issue by Shaggy84675** [voxeltycoon/bug-tracker#173]
**Describe the bug**
In the picture you can see, when I want to place the warehouse, it shows which mining facilities it should cover. However even the two coal mines on the left are highlighted, the coal isn't placed into the red warehouse. (It's highlighted red, because there's already one)

![obrazek](https://user-images.githubusercontent.com/1374803/84581761-0d458f80-ade5-11ea-8538-68f860b6ea69.png)

**Steps to reproduce**
Build a warehouse as far (the building is highlighted) as you can from the mining facilities.

**Build version**
0.84.1.132359349156935096 itch

**Platform**
Windows 10 1909 build 18363.900

**Reproducibility**
every time

**Comment by andrewpey** [comment]
Should be fixed in 
[0.85](https://voxeltycoon.xyz/changelog#0.85).
