### ISSUE TITLE
Blurry UI text inconsistencies Linux

### ISSUE THREAD

**Issue by ghost** [voxeltycoon/bug-tracker#174]
**Describe the bug**
Some of the menu text is blurry, some isn't. UI blur effect and anti-aliasing have no effect.

**Steps to reproduce**
Launch the game in Linux.

**Build version**
0.84.1.132359349156935096 itch

**Platform**
Arch Linux x86_64 
Kernel: 5.7.5-arch1-1 

**Reproducibility**
Always
![Screenshot_20200626_135524](https://user-images.githubusercontent.com/14079526/85854861-836ace80-b7b5-11ea-829a-231b6c8d6632.png)

**Comment by andrewpey** [comment]
Not related to Linux, it's a common issue we have to fight in specific cases.

Feel free to open issues for exact places where you find blurry texts (other than those on the screenshot above).
