### ISSUE TITLE
Bad performance late game

### ISSUE THREAD

**Issue by morgun** [voxeltycoon/bug-tracker#175]
**Describe the bug**
Bad performance late game when game is not paused, something tanks performance. If you look closely to the video, you'll see that on pause game uses 30%+ CPU and one unpaused cpu usage drop to <25% as well as framerate goes under 60.

Save is available here: https://drive.google.com/file/d/1O0mMaJ-sVbpoxeBe-a3LoRa9uu30g4u6/view?usp=sharing
Video feed is available here: https://streamable.com/suv8sz
PC configuration can be seen in the video.

**Steps to reproduce**
Play a game for a long period of time,

**Build version**
0.84.1.132359349156935096 itch

**Platform**
Windows 10 Pro v.2004

**Reproducibility**
Every time

**Comment by morgun** [comment]
Seems like game is bottlenecked by some kind of thread sync when unpaused.
Like game render and physics thread are in synchronous mode.
I there any profiling tool to see what tanks the performance?

**Comment by andrewpey** [comment]
Duplicate #75.
