### ISSUE TITLE
Station window too tall with many covered  warehouses, associated trains

### ISSUE THREAD

**Issue by daiwai** [voxeltycoon/bug-tracker#177]
If there are many warehouses and trains belonging to a station it seems like the station window height is incorrectly calculated thus causing the last few associated trains to be inaccessible.

The station window should never grow taller than the screen height.

![tall_station_window](https://user-images.githubusercontent.com/683371/90310351-13dda980-def1-11ea-9b6c-7e7101467b9d.png)

**Steps to reproduce**
Build many warehouses within the range of a station and have that station be a destination of many trains (Presumably, the exact number of needed warehouses/trains to trigger this behaviour depends on the screen resolution and/or window size)

**Build version**
0.84.1.132359349156935096 itch

**Platform**
OS name and version.

**Reproducibility**
every time

**Comment by andrewpey** [comment]
Thanks, this will be worked on.

**Comment by andrewpey** [comment]
Should be fixed on [0.85](https://voxeltycoon.xyz/changelog#0.85).
