### ISSUE TITLE
Cloning a train with a route from a station's menu makes it show up under individual route

### ISSUE THREAD

**Issue by supperbas** [voxeltycoon/bug-tracker#180]
**Describe the bug**
Cloning a train with a route from a station's menu makes it show up under individual route.

**Steps to reproduce**
When you open a station's menu, and clone a train that has an route. By opening the depot menu and clicking the train, in the station's menu. Then the train will show up in the station's overview but under "individual route". When you add a 2nd train (the 1st train will show up correctly and the 2nd train shows up under individual route.). Closing the station's interface resolves the issue. Seems like when a train is added its route is not checked, unless it was already linked to the station.

**Build version**
V0.84.1

**Platform**
Windows

**Reproducibility**
Every time/once

**Logs/saves**
on request

**Comment by katepolak** [comment]
Unless I am misunderstanding the issue this seems to have been fixed in 0.85 so I am closing this issue.
