### ISSUE TITLE
Game crashes on region unlock

### ISSUE THREAD

**Issue by JOSHUASAMPSON** [voxeltycoon/bug-tracker#183]
**Describe the bug**
when buying new zones(land) it loads for about 3 minutes crashes then loads back into game as normal or it totaly crashes the game
**Steps to reproduce**
buy any land wait 3 mintues either click or wait and it will crash reboot and back to normal or just crash
**Build version**
Pre-alpha 
**Platform**
windows microsoft

**Reproducibility**
all the time

**Logs/saves**
new games or saves doesnt matter always does it

**Comment by andrewpey** [comment]
Can we see [the logs](https://github.com/voxeltycoon/bug-tracker#logs)?

Also, it would be great if you change the issue title to something more descriptive.

**Comment by JOSHUASAMPSON** [comment]
hey very sorry just got into emails  i had trouble describing the problem
and i didnt know what you wanted in the title so i just put voxel tycoon
i guess i would say when you go to buy new land when you buy it its will
continually load for a few minutes and sometimes it will crash or crash and
restart so it gets to the point where if you click during the loading
process it will act like its crashing your game it says do want to end the
process     if you give it a few seconds it usually goes away and your free
to play again or in some of the case it totally crashes your game

happens all the time every single time i buy land same thing happoens


how do i give you the logs?

kind regards

**Comment by andrewpey** [comment]
First, run the game until it crashes.

Just after that happened, attach the file named `Player.log` which can be found at this path: `%appdata%/../LocalLow/VoxelTycoon/VoxelTycoon/` (you can just paste this address into the File Explorer address bar).

Thank you.
