### ISSUE TITLE
Notification sound not playing after loading game from code while sending a notification

### ISSUE THREAD

**Issue by ndelta0** [voxeltycoon/bug-tracker#185]
**Describe the bug**
After calling
`LoadGameHelper.TryLoad(SaveMetadataFull);`
and pushing a notification directly after/before, the game stops playing the notification sound on every subsequent notification.

**Steps to reproduce**
1. Start new game/load a game
2. Call the provided code

**Build version**
0.84.1.132474991604612990 itch

**Platform**
Windows 10 Home, version 20H2, OS build 19042.630, Windows Feature Experience Pack 120.2212.31.0

**Reproducibility**
Every time

**Logs/saves**
Log: [On Pastebin](https://pastebin.com/1mNbrrRw)
Save: Any
Code:
```csharp
private static void DataReceivedAsServer(object sender, DataReceivedEventArgs e)
{
    NotificationManager.Current.Push($"Client {e.Client.Id}", $"{e.Message.Body.Command}:\n{Utils.ByteArrayToHexString(e.Message.Body.Content)}", null);
    switch (e.Message.Body.Command)
    {
        default:
        case MessageCommand.Unknown: // Problem occurs because of code in this switch case
            var path = Path.Combine(_saveDirectory, "testfilename.sav");
            SaveMetadataFull meta = (SaveMetadataFull)SaveSerializer.ReadMetadata(path, true);
            meta.Filename = "testfilename.sav"; // By the way, why isn't the Filename property set? Every time it was 'null'
            LoadGameHelper.TryLoad(meta);
            break;
    }
}
```

**Comment by andrewpey** [comment]
Is it ensured that `DataReceivedAsServer` called on the main thread?

> By the way, why isn't the Filename property set? Every time it was 'null'

Filename is not written to binary data, so it can't be obtained on reading. It's set from a caller code if available.

In your case, your code is a caller code, so you do it just right.

However, probably we can change `ReadMetadata` API so it will always set the filename from the provided path instead.

**Comment by ndelta0** [comment]
> Is it ensured that DataReceivedAsServer called on the main thread?

To be honest I don't know, almost sure that it's not, as it's called this way: Socket's Asynchronous ReceiveCallback > ClientController's OnDataReceived > DataReceived event to which the method is attached. That would mean I need to set some kind of flag with a data attached to it and call this method from Update or LateUpdate method right?

On the note of the ReadMetadata, it can be a bit confusing using it at first as the default path is the installation location instead of the saves folder.
> However, probably we can change ReadMetadata API so it will always set the filename from the provided path instead.

It would be nice if it isn't much trouble, it would really only remove one line of code for the modder but it's always a welcome change in my opinion.

EDIT: It could be nice if there was a "failsafe" in the API, like checking if current thread is main thread and throwing an exception.

**Comment by ndelta0** [comment]
Update, now the sound works even after changing the level, but now the exceptions are thrown even without changing the level [as you can see here](https://pastebin.com/xwiHZyhS). I tried reinstalling the game along with removing the folder in LocalLow. The only thing I did was moved the code to OnUpdate method and wrapping it in an if statement.

**Comment by andrewpey** [comment]
> On the note of the ReadMetadata, it can be a bit confusing using it at first as the default path is the installation location instead of the saves folder.

Yeah, as you can probably saw from the code we usually use it in conjunction with `GetAllMetadata` which returns data with correct filenames filled in.

**Comment by andrewpey** [comment]
> That would mean I need to set some kind of flag with a data attached to it and call this method from Update or LateUpdate method right?

Correct, you need to push your data to be available to read from the main thread somehow. Check this thread:
https://answers.unity.com/questions/305882/how-do-i-invoke-functions-on-the-main-thread.html

> It could be nice if there was a "failsafe" in the API, like checking if current thread is main thread and throwing an exception.

All Unity APIs should be called from the main thread, this is how Unity works. So, currently, we expect that our APIs are also called from the main thread (as they use Unity APIs in turn). But we will look into the failsafe option, thanks.

**Comment by ndelta0** [comment]
Okay, I fixed the issue by adding the socket's data received callback to the action list that is iterated through in the OnUpdate method, as the NotificationManager.Push method is also causing the exception with the main thread.
