### ISSUE TITLE
Train Pathing issue

### ISSUE THREAD

**Issue by pietballas** [voxeltycoon/bug-tracker#186]
Trains stuck leaving the intersection although nothing blocking train path to next block.

![image](https://user-images.githubusercontent.com/76472259/102868778-4c633600-4443-11eb-97ca-c0787fe625a0.png)

 The issue might be caused by the the 2 way junction.

![image](https://user-images.githubusercontent.com/76472259/102869021-b380ea80-4443-11eb-98e9-a67be353edcf.png)

Added savegame for reference.

[7vy6e0cdyay.zip](https://github.com/voxeltycoon/bug-tracker/files/5728802/7vy6e0cdyay.zip)

**Comment by pietballas** [comment]
Issue found rails to close to each other at bend, dev's on discord solved the problem, thanks :)

**Comment by victorleblais** [comment]
This is not a bug, it is working as intended.

Explanation if anyone wonders why it's closed:
The diagonal tracks in the back of the image are too close to each other. Trains could clip/collide if they were to drive on both sides, so the game consider it to be part of the same block even though they're not linked together.

Here's a visualisation of the different blocks in this image, the problematic spot is circled in red.
![image](https://user-images.githubusercontent.com/4365075/102877402-fa241400-4446-11eb-846c-71320075b29e.png)
