### ISSUE TITLE
"continue save" dosnt disappear after deleting all save files

### ISSUE THREAD

**Issue by hasezoey** [voxeltycoon/bug-tracker#190]
**Describe the bug**
When trying to load a save after deleting all (with ingame-menu) and clicking "Continue" fails with "Cant load saved game"

**Steps to reproduce**
1. create a save
2. re-start game (i dont know if needed, but that is what i had done)
3. click on "load save" and then delete all saves in there
4. "Continue" button dosnt disappear, and when clicking it, it loads, until it fails with "Cant load saved game"

**Build version**
v0.85 (0.85.0.24 steam)

**Platform**
Linux Mint 20.1

**Reproducibility**
only tried once, but i think it always happens

**Logs/saves**
any save should do

PS:
i found this because i downloaded the steam version right when it came out, tried some stuff, came back later to delete all saves and start a new actual game, and was curious why the "Continue" button did not disappear

**Comment by andrewpey** [comment]
Fixed in [0.85.1](https://voxeltycoon.xyz/changelog#0.85.1).
