### ISSUE TITLE
NRE when editing keybindings

### ISSUE THREAD

**Issue by Garagoth** [voxeltycoon/bug-tracker#191]
**Describe the bug**
While editing key bindings I assigned Q to "Rotate left". Then UI displayed red bug icon in top-right with NRE (see attached log file).
(The log file also whows some other issues, like sqlite3.so missing?)
After that no further keys can be assigned, but closing setting window and opening it again allows for one edit again.

**Steps to reproduce**
Change key binding

**Build version**
0.85.0.24 steam

**Platform**
Linux

**Reproducibility**
Every time.

**Logs/saves**
[Player.log](https://github.com/voxeltycoon/bug-tracker/files/6319866/Player.log)

**Comment by andrewpey** [comment]
Should be fixed in [0.85.1](https://voxeltycoon.xyz/changelog#0.85.1).
