### ISSUE TITLE
Refitting trucks does not immediately update icon in UI. 

### ISSUE THREAD

**Issue by ewulff** [voxeltycoon/bug-tracker#192]
**Describe the bug**
After refitting trucks in a depot the icons denoting cargo type do not change in the depot view. This makes it hard to determine which trucks have been refitted and which haven't. It seems to update later after other actions have happened.

**Steps to reproduce**
Send a bunch of trucks to the depot (in my case 8-10).
Configure truck and select a single cargo type (instead of auto) (I did all of this with AAA wood trucks)
Try and find the reconfigured one in the list based on icon (not that easy)

**Build version**
0.85.0.24 steam

**Platform**
Windows Version	10.0.19041 Build 19041

**Reproducibility**
Uh every time I've tried it

**Logs/saves**
Doubt this is applicable.

**Comment by andrewpey** [comment]
Fixed in [0.85.1](https://voxeltycoon.xyz/changelog#0.85.1).
