### ISSUE TITLE
after signal construction the train can no longer find a route

### ISSUE THREAD

**Issue by Jack9183** [voxeltycoon/bug-tracker#194]
After I have built a track and the train runs on it, everything works without problems. Before a station that is approached by 2 different trains I have built signals so that they do not collide in the station. But as soon as the signal stands, the trains drive no more meter. Only when I tear off the signals they go again.
![grafik](https://user-images.githubusercontent.com/67862901/114952770-444a5e80-9e57-11eb-87fd-629f0ddd9b3f.png)

![grafik](https://user-images.githubusercontent.com/67862901/114952815-65ab4a80-9e57-11eb-8030-c814786c21ff.png)

**Comment by victorleblais** [comment]
Trains cannot cross signals from the back side. They automatically act like a "wrong-way" sign, if you will.

If you want trains to be able to go both ways, place another signal on the same piece of track in the going direction in such a way that the two arrows are together, like this:
![image](https://user-images.githubusercontent.com/4365075/114953078-e9fdcd80-9e57-11eb-89a9-1a11b9f7f370.png)
