### ISSUE TITLE
Company window shows configured (but not bought) train as owned

### ISSUE THREAD

**Issue by ndelta0** [voxeltycoon/bug-tracker#201]
**Describe the bug**
The company overview window shows 1 more train when buying a train (configuring).

**Steps to reproduce**

1. Open company overview window
2. Open train configuration window in depot
3. Configure the train but not buy it
4. The Owned trains amount in the company window is 1 bigger than actual owned amount

**Build version**
0.85.0.24 steam

**Platform**
N/A

**Reproducibility**
Every time

**Logs/saves**
N/A

**Comment by katepolak** [comment]
Can confirm this is the case.

**Comment by andrewpey** [comment]
Fixed in [0.85.1](https://voxeltycoon.xyz/changelog#0.85.1).
