### ISSUE TITLE
trucks lose what their routes on start up after exiting the game and coming back

### ISSUE THREAD

**Issue by Duhs0001** [voxeltycoon/bug-tracker#208]
every time i leave and comeback to my game, the trucks seem to lose their route and how to follow it. they start going too all different stations. 

i fully close the game and or shut my computer of, after saving. then i come back to play and notifcations say trucks are not making money because one gets stuck and cannot unload. when i go in to check why its happening. it is due to the trucks not going to stations they were assigned and cant drop off the resources due to station not needing them 
**Describe the bug**
A clear and concise description of what the bug is. If applicable, add screenshots or video to help explain your problem.

**Steps to reproduce**
Steps to reproduce the behavior.

**Build version**
Version information can be found at the bottom of the settings window.

**Platform**
OS name and version.

**Reproducibility**
How often an issue reproduces: every time, often, rare, once.

**Logs/saves**
Attach [logs or saves](https://github.com/voxeltycoon/bug-tracker/blob/master/README.md#logs) if applicable.

**Comment by victorleblais** [comment]
Are you making sure to save your game before closing it?

Can you try to share your save file (loading menu -> "..." on your save -> share) and upload it to something like Google Drive, Dropbox or WeTransfer?

**Comment by andrewpey** [comment]
Closing since no info provided.
