### ISSUE TITLE
User has the option to continue a saved game after it has been deleted

### ISSUE THREAD

**Issue by Rich-Dunne** [voxeltycoon/bug-tracker#213]
**Describe the bug**
After deleting a saved game, the main menu still shows the option to continue the deleted save.  When the user selects this option, the game will spend time attempting to load the save, then produce an error message that the save file is missing.  The user is returned to the home screen with the menu option now gone.  The option should be removed when the save game is first deleted.

**Steps to reproduce**
1.  Create and save a new game
2.  Return to the main menu and delete the save
3.  Choose the continue game option

**Build version**
0.85.0.24 Steam

**Platform**
Windows 10 19041.928

**Reproducibility**
Every time

**Logs/saves**
[Player.log](https://github.com/voxeltycoon/bug-tracker/files/6329966/Player.log)

**Comment by katepolak** [comment]
Thanks for the report, but this has already been reported in #190 so next time please make sure to look for existing issues before posting duplicates.
