### ISSUE TITLE
Tutorial - Can't complete the "build a station" objective

### ISSUE THREAD

**Issue by Timothy606** [voxeltycoon/bug-tracker#216]
**Describe the bug**
During the first tutorial I wasn't able to complete the build a station objective. After building the coal mine the next objective was to build a station. But after building my station following the mentioned steps (and having the station be build in close proximity of the coal mine, it did not complete the objective.

**Steps to reproduce**
1. Start a new game
2. Follow the first tutorial
3. Build a coal mine
4. Build a station near the coal mine
5. Notice the Continue option does not become green.

**Build version**
0.85.0.24 steam

**Platform**
Window 10.0.19042

**Reproducibility**
2 out of 2 times

**Logs/saves**
Attach [logs or saves]([Player.log](https://github.com/voxeltycoon/bug-tracker/files/6330065/Player.log)
[Player.log](https://github.com/voxeltycoon/bug-tracker/files/6330068/Player.log)
#logs) if applicable.

Thanks 👍

**Comment by Garagoth** [comment]
Train station or truck station, because tutorial needs a truck station?

**Comment by Timothy606** [comment]
I likely build the wrong station, sorry
