### ISSUE TITLE
Trucks losing there route and priority material 

### ISSUE THREAD

**Issue by Justin1923** [voxeltycoon/bug-tracker#225]
As the day (Month) changes some trucks (about 3 to 4) change the route given and the material I have chosen for them to transport.  I must go in and redo both for each truck every new day.

Regards

**Comment by IDragonfire** [comment]
Did you use the `auto-storages` for your trucks or did you lock it? 
Did you use the `refit` action?

**Comment by Justin1923** [comment]
I have done both but now that I have played even more I think it might have simply been set as the auto.  I have now gone in each time and picked a material to lock it and it has been successful so far.

I'm not familiar with the refit action.  I will have to look into that.

Thanks for the quick response
