### ISSUE TITLE
Track Detection Issue

### ISSUE THREAD

**Issue by SheepShifterLord** [voxeltycoon/bug-tracker#227]
### The Problem
Whenever two diagonal tracks are very close to each other (Those two tracks are not connected to each other). The game assumes that those two tracks are one lane which messes up the signaling. When the trains come on to the signal, the train will stop for the other train on another lane. This will happen every time.

### How To Recreate
Put two tracks side by side diagonally and test out the signaling around it.

**_Extra Info_**

OS: Windows 10
Build Version: 0.85.0.24 steam

**Comment by victorleblais** [comment]
This is working as intended: the tracks are too close to each other for trains to go safely, so the count as a single block.
