### ISSUE TITLE
Game crash while unpausing with the station tool selected

### ISSUE THREAD

**Issue by NgeNoir** [voxeltycoon/bug-tracker#233]
**Describe the bug**

The game crashes during the construction of a train station 

**Steps to reproduce**

1. I set Pause the game
2. Select a railway station in the construction menu
3. A layout of the future station appears at the cursor location
4. With the mouse I click on to unpause and at the same time do not cancel the construction of the station.
5. The game crashes 

**Build version**
v 0.85

**Platform**
Win 10 pro

**Reproducibility**
3 times

**Logs/saves**
Attach [logs or saves](https://github.com/voxeltycoon/bug-tracker/blob/master/README.md#logs) if applicable.

**Comment by katepolak** [comment]
I am not able to reproduce this bug on my end. Do I understand correctly that the crash happens when you click the red "paused" button while having the station tool selected?

**Comment by NgeNoir** [comment]
Yes, of course! But i have this bug only 3 times in new game, and now its gone.  22.04.2021, 21:53, "Jan Polák" ***@***.***>: I am not able to reproduce this bug on my end. Do I understand correctly that the crash happens when you click the red "paused" button while having the station tool selected?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  -- Яндекс.Почта — быстрая почтаhttp://mail.yandex.ru/neo2/collect/?exp=1&t=2
