### ISSUE TITLE
Vehicle details not updated properly when reconfigured

### ISSUE THREAD

**Issue by katepolak** [voxeltycoon/bug-tracker#24]
**Describe the bug**
If you have a vehicle window open on the details page, upon re-configuring the vehicle the details don't get updated accordingly. The numbers change, but the cart list bellow doesn't.

![image](https://user-images.githubusercontent.com/11616898/57075222-7b64eb00-6ce6-11e9-8227-2efea9e205b9.png)
Example of the bug, top speed says 140 kmh but the engine shown bellow has a max speed of 80 kmh.

**Steps to reproduce**
Open a vehicle details page and while keeping it open reconfigure the vehicle and observe the details not updated properly.

**Build version**
0.53 2019-05-01 PRE-ALPHA

**Platform**
Windows 10 1903

**Reproducibility**
Every time

**Comment by Phelzier** [comment]
**Describe the bug**
I have a train with two locomotives facing the same way.  After editing the train and flipping the end locomotive to face the opposite way, the HUD did not reflect these changes.  Closing the HUD and reopening showed the locomotive in the correct direction.

**Steps to reproduce**
Edit train with two engines.  Flip the engine.

**Build version**
0.71 2019-06-26

**Platform**
Windows 10 17763.557

**Reproducibility**
Every time


![bug](https://user-images.githubusercontent.com/22050004/60390012-eb180c00-9ac4-11e9-91ed-c2cef006ea6e.png)

**Comment by andrewpey** [comment]
The original issue is fixed with 
[0.85](https://voxeltycoon.xyz/changelog#0.85).

The issue reported by Phelzier (#76) is unrelated.
