### ISSUE TITLE
Unable to create Iron Bars

### ISSUE THREAD

**Issue by kaomoneus** [voxeltycoon/bug-tracker#245]
**Describe the bug**
Unable to make manufacture produce Iron Bars

**Steps to reproduce**
1. I have built a manufacture
2. I built station
3. Selected a receipt (Iron Bar)
4. Built iron and coal warehouses nearby
5. Scheduled iron and coal trucks to station
Expected: I though those steps are enough to start manufacturing
Actual: Factory gets no resources

**Build version**
0.85.1

**Platform**
MBP Late 2013

**Logs/saves**
[8ztuagbt3qh.zip](https://github.com/voxeltycoon/bug-tracker/files/6372710/8ztuagbt3qh.zip)

* Once you open saved game you should see in frame all described buildings
* Game is paused.

**Comment by asiaclonk** [comment]
Manufacturing uses transport belts to move items. You have to place connectors to the warehouses and use belts to feed the materials into the factory buildings and to lead products back into another warehouse. Make sure the belt direction is correct too.
