### ISSUE TITLE
Blocks of empty terrain

### ISSUE THREAD

**Issue by goldenarrow** [voxeltycoon/bug-tracker#25]
**Describe the bug**
Blocks of empty terrain, fairly central to the region, on loading a new game. Disappear if terraformed or even previewing a terraform.

![image](https://user-images.githubusercontent.com/38834964/57197371-64303280-6f5e-11e9-8908-2fc9c72b463a.png)

[Player.log](https://github.com/voxeltycoon/bug-tracker/files/3145808/Player.log)

**Steps to reproduce**
Unknown. Seems to happen on random new games. Not visible on re-entering saved game.

**Build version**
0.53 2019-05-01

**Platform**
Windows 7

**Reproducibility**
Frequently.

**Comment by goldenarrow** [comment]
Follow up.

First time I've seen this happen in a loaded saved game. Same region as above, but much later on. 
![image](https://user-images.githubusercontent.com/38834964/57220661-1b2abd80-6ff4-11e9-91bb-7cefb47eeadc.png)

Interestingly on this one, I can't clear it using the 'level' terrain tool. Building more track doesn't clear it, nor does planting trees.

Raising terrain did however clear it.

**Comment by andrewpey** [comment]
Might be hardware issue? We couldn’t reproduce it unfortunately. Closing for now.
