### ISSUE TITLE
Train previews bugged in depot window

### ISSUE THREAD

**Issue by EsquimaltNanaimo** [voxeltycoon/bug-tracker#34]
**Describe the bug**
When a train is in a depot, flipped units have backwards previews.
![2-1](https://user-images.githubusercontent.com/34557490/58230871-69c1a280-7cea-11e9-9d7b-61b470ef9077.png)
Foreground (train setup) window shows the larger locomotive in its correct orientation. Depot window (behind) shows it backwards.

**Steps to reproduce**
Flip a locomotive in the depot.

**Build version**
0.56

**Platform**
Windows 7 x64

**Reproducibility**
Every time.

**Comment by andrewpey** [comment]
Fixed in 0.58
