### ISSUE TITLE
Replaced wagon does not update in train details

### ISSUE THREAD

**Issue by tomdotio** [voxeltycoon/bug-tracker#41]
**Describe the bug**
When you replace a wagon to another type, this is not updated in the train details tab.

**Steps to reproduce**
As above

**Build version**
0.70 2019-06-25 itch prealpha

**Platform**
W10

**Reproducibility**
Every time

**Comment by katepolak** [comment]
Duplicate. Probably should be closed and instead added as a comment to #24

**Comment by tomdotio** [comment]
Sorry, I will double check next time it the bug was already posted! :)

**Comment by katepolak** [comment]
No worries ;)
