### ISSUE TITLE
Train sometimes teleports to depot

### ISSUE THREAD

**Issue by tomdotio** [voxeltycoon/bug-tracker#42]
**Describe the bug**
When sending trains to the depot, they sometimes teleport. At one point a train teleported away from the station.

**Steps to reproduce**
Send a train to the depot.

**Build version**
0.70 2019-06-25 itch prealpha

**Platform**
W10

**Reproducibility**
Often

**Comment by katepolak** [comment]
I am not sure what exactly you mean. Teleport is the only way for trains to get to depots currently. So if you ever saw a train actually pathfind to it than that's what's actually the bug.

**Comment by tomdotio** [comment]
Ok, good to know. Just from playing other games I assumed, they will drive to the selected depot. In that case I will close the bug.

**Comment by Antaguana** [comment]
Perhaps change this "bug" to a suggestion to make them pathfind?
Trucks do the same thing, when they stop in the middle of the road to prepare for teleportation they create traffic jams.

**Comment by katepolak** [comment]
It's planned to be implemented later.

**Comment by kristofeI** [comment]
Yeah, this teleportation looks very strange.

**Comment by Garagoth** [comment]
Still happens now (at least with trucks) in Steam EA version.
