### ISSUE TITLE
the game does not start when the mode "trailers pack" is enabled

### ISSUE THREAD

**Issue by MaximDementyev** [voxeltycoon/bug-tracker#43]
**Describe the bug**
![2019-06-28_18-18-01](https://user-images.githubusercontent.com/15971031/60354382-c6dd0200-99d4-11e9-9019-9ee487f956b6.png)

**Steps to reproduce**
run the game with the mod enabled "Trailers pack"

**Build version**
pre-alpha

**Platform**
windows 10

**Reproducibility**
every time

**Comment by katepolak** [comment]
That's an issue with the mod, not with the game and thus it doesn't belong here. Please report it to the mod creator.
