### ISSUE TITLE
Crash when alt-tabbing while loading

### ISSUE THREAD

**Issue by Quintentje1998** [voxeltycoon/bug-tracker#44]
**Describe the bug**
crashes when loading a world and alt-tabbing

**Steps to reproduce**
load a new world and alt-tab while loading while fullscreen

**Build version**
0.71 2019-06-26 itch pre-alpha

**Platform**
windows 10

**Reproducibility**
once for now

**Comment by katepolak** [comment]
Could you please provide logs of the game after the crash? You can find the file in this location: `%appdata%/../LocalLow/VoxelTycoon/VoxelTycoon/Player.log`

**Comment by katepolak** [comment]
I can't seem to replicate this issue, I can tab both in and out without the game crashing.

**Comment by andrewpey** [comment]
Closing this for now.
