### ISSUE TITLE
Drag feature to change placement/sort order of trains in editor window.

### ISSUE THREAD

**Issue by jordanchoklad** [voxeltycoon/bug-tracker#47]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by katepolak** [comment]
Thanks for your suggestion. Could you please edit the body of the message to describe it shortly? The template is there for a reason. Thanks

**Comment by jordanchoklad** [comment]
Sorry for being new at this. Was just trying to help.

**Comment by katepolak** [comment]
Don't worry, you can edit the message to include the new details. Or if you want I can do it myself if you aren't sure how to do it.
