### ISSUE TITLE
Game won't start on Linux, Ubuntu 18.04

### ISSUE THREAD

**Issue by No-user-name-left** [voxeltycoon/bug-tracker#48]
[Player.log](https://github.com/voxeltycoon/bug-tracker/files/3340058/Player.log)
**Describe the bug**
Game won't start on Linux, Ubuntu 18.04 Not via Itch nor command line.

**Steps to reproduce**
Start game via Itch launcher or try to start downloaded game via command line.
Errors:
(VoxelTycoon:22256): GLib-GObject-WARNING **: 17:32:24.783: cannot register existing type 'GtkBuildable'

(VoxelTycoon:22256): GLib-GObject-CRITICAL **: 17:32:24.783: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(VoxelTycoon:22256): GLib-CRITICAL **: 17:32:24.783: g_once_init_leave: assertion 'result != 0' failed

(VoxelTycoon:22256): GLib-GObject-WARNING **: 17:32:24.785: cannot register existing type 'GtkWidget'

(VoxelTycoon:22256): GLib-GObject-WARNING **: 17:32:24.785: cannot add class private field to invalid type '<invalid>'

(VoxelTycoon:22256): GLib-GObject-WARNING **: 17:32:24.785: cannot add private field to invalid (non-instantiatable) type '<invalid>'

 

**Build version**
Pre Alpha

**Platform**
Ubuntu 18.04

**Comment by katepolak** [comment]
This seems like a Unity issue to me as it's coming directly from GTK which Unity doesn't even give access to.

**Comment by No-user-name-left** [comment]
Found out that it doesn't run on KDE-Plasma but it does on Gnome! Not sure what's going on here.

**Comment by katepolak** [comment]
At least it works now. We might have to report this to Unity, but first we have to do a bit more investigating. Will close the issue but might update it later if we get new information.
