### ISSUE TITLE
Schedule setup remained open to add stations

### ISSUE THREAD

**Issue by parakanastika** [voxeltycoon/bug-tracker#54]
**Describe the bug**
Unable to exit the scheduler - using ESC / close window disabled

**Steps to reproduce**
1. Open Truck Schedule
2. add station
3. unable to exit the schedule 

**Build version**
0.71 2019-06-26 ITCH PRE-ALPHA

**Platform**
Windows 10 Pro x64

**Reproducibility**
Once
[VoxelTycoon.zip](https://github.com/voxeltycoon/bug-tracker/files/3340198/VoxelTycoon.zip)

**Comment by ErwinBeen** [comment]
Had the same issue today. 
STR:
1. Bought a new truck
2. Clicked on the truck to open schedule
3. Form gets unresponsive

4. Tried 'sell all', to sell the vehicle in the Garage
5. Tried to buy new truck, costs 14 million and truck image in buy form renders incorrectly
5.1 Also cannot click the buy button for the new truck.

_Reloading the game resolves the issue_

![truckbug](https://user-images.githubusercontent.com/21125144/60536322-45ec7600-9d06-11e9-8c58-c91901577298.JPG)

**Comment by katepolak** [comment]
Fixed in 0.72
