### ISSUE TITLE
Add confirmation dialog to deleting

### ISSUE THREAD

**Issue by MaximDementyev** [voxeltycoon/bug-tracker#55]
**Is your feature request related to a problem? Please describe.**
all objects, even very expensive are removed without confirmation

**Describe the solution you'd like**
I want to see confirmation of deleting large objects. for example railway stations

**Describe alternatives you've considered**
absent

**Additional context**

**Comment by katepolak** [comment]
Could you please change the description to use the suggestion template? It is there for a reason.

**Comment by MaximDementyev** [comment]
![2019-06-28_20-51-37](https://user-images.githubusercontent.com/15971031/60361330-9736f580-99e6-11e9-988d-c0fdbd729e8a.png)
how to choose? I create through Suggestion
you mean I need to fill out 4 fields?

**Comment by katepolak** [comment]
That's correct, but I see you used it for new ones already. Could you also update the old ones? Just copy the template over and fill it in.

**Comment by katepolak** [comment]
Requested by more people on Discord.

**Comment by katepolak** [comment]
Implemented in 0.72
