### ISSUE TITLE
it is impossible to build a railway crossing on diagonal paths

### ISSUE THREAD

**Issue by MaximDementyev** [voxeltycoon/bug-tracker#57]
**Describe the bug**
if the two paths are located at a distance, as in the figure, then if the paths are horizontal or vertical, you can build a move from one path to another. If the paths are angled, the crossing cannot be built
![2019-06-28_21-13-15](https://user-images.githubusercontent.com/15971031/60362890-ba63a400-99ea-11e9-835a-512daf253802.png)
![2019-06-28_21-13-32](https://user-images.githubusercontent.com/15971031/60362891-ba63a400-99ea-11e9-8611-f2744e90ad1f.png)

**Steps to reproduce**
build paths as shown

**Build version**
v0.71 pre-alpha

**Platform**
windows 10

**Reproducibility**
every time

**Comment by katepolak** [comment]
This can't be fixed, it's just how the rail system works. If you really need Xs on diagonals you have to space the rails more.
