### ISSUE TITLE
Built road curve looks strange if the mouse is a bit over the curve

### ISSUE THREAD

**Issue by regstar** [voxeltycoon/bug-tracker#59]
**Describe the bug**
Built a curve for my road and connected it together. It looks strange after it snaps together when you build a bit more road. See screenshot.

**Steps to reproduce**
Built two roads. After you want to connect it together it gets a strange look. If your mouse is a bit over the curve, you get this strange road. 

**Build version**
0.71 2019-06-26

**Platform**
Windows 10

**Reproducibility**
Every time

What its looks like:
![Anmerkung 2019-06-28 204059](https://user-images.githubusercontent.com/16978972/60364350-33143180-99e6-11e9-8bb4-db0064bed6eb.png)

Reproduce Step 1:
![Screenshot (4)](https://user-images.githubusercontent.com/16978972/60364496-a158f400-99e6-11e9-81e5-5eee82469f7f.png)

Step2:
![Screenshot (5)](https://user-images.githubusercontent.com/16978972/60364543-ba61a500-99e6-11e9-9233-2a59d8600814.png)

Step 3:
![Screenshot (6)](https://user-images.githubusercontent.com/16978972/60364556-c77e9400-99e6-11e9-8d16-cef9688e8a94.png)

Step 4:
![Screenshot (7)](https://user-images.githubusercontent.com/16978972/60364579-d402ec80-99e6-11e9-99bb-0bc91a07843d.png)

If u builds this like the steps above, you get the strange road seen on the first screenshot.

**Comment by regstar** [comment]
Sry the mouse cursor is not be shown on these screenshots. But I hope you can reproduce this easily.

**Comment by katepolak** [comment]
Thanks for the report. This is a known issue which is way bigger than just this single case. I will most likely make a more general bug report about it at some point but for now let's keep this one.

Fixing this will require rewriting a lot of the road related code so it will take time.

**Comment by regstar** [comment]
Ah... thx :) Is there a known bug list, that I don't spell duplicated bugs?

**Comment by katepolak** [comment]
Just search the other ones on here. But there are few that aren't here yet, I will add them when I can.

**Comment by voxeltycoon** [comment]
Fixed in 0.74.
