### ISSUE TITLE
[Linux] Zooming in/out inverted in newest build

### ISSUE THREAD

**Issue by felixactually** [voxeltycoon/bug-tracker#6]
On the `slow` branch scrolling the mousewheel up (towards your monitor) zooms in and scrolling it down (towards you) zooms out, as expected. However, on the `nightly` branch it is inverted. (Note by Maxim: Possibly related to upgrade to next major Unity version).

**Comment by andrewpey** [comment]
Spotted on Linux, not affects Windows.

**Comment by andrewpey** [comment]
Not affecting MacOS as well.

**Comment by andrewpey** [comment]
Confirmed that this is a regression caused by upgrading to Unity 2019.1 (not reproducible in builds made with 2018.3). Filled a bug report to Unity, currently exploring ways to workaround.

**Comment by andrewpey** [comment]
Unity issue: https://issuetracker.unity3d.com/issues/linux-input-dot-mousescrolldelta-returns-reversed-values-in-linux-player

**Comment by andrewpey** [comment]
Deployed a workaround in **0.53**. Should work for both zooming and scrolling in lists.

Closing this until Unity will be able to fix it.

**Comment by andrewpey** [comment]
Fixed in Unity Unity 2019.3.0a3 (https://issuetracker.unity3d.com/issues/linux-input-dot-mousescrolldelta-returns-reversed-values-in-linux-player). Until then, workaround stays applied.
