### ISSUE TITLE
Pressing movement key on saving will move the camera 

### ISSUE THREAD

**Issue by regstar** [voxeltycoon/bug-tracker#67]
**Describe the bug**
On autosave or on manually save will show up a saving box. If you use the control keys "wasd" on the keyboard, it will move the camera (hidden behaviour) in the background. If saving complete the camera will jump to this location.

**Steps to reproduce**
Save, press "wasd" and the camera will jump to the location after saving dialog disappeared.

**Build version**
0.71

**Platform**
Windows 10

**Reproducibility**
every time

**Comment by andrewpey** [comment]
Fixed in [0.85](https://voxeltycoon.xyz/changelog#0.85).
