### ISSUE TITLE
You can place signals inside depots

### ISSUE THREAD

**Issue by drewtato** [voxeltycoon/bug-tracker#68]
Here you can see the green dot that usually helps with placing signals on rails.

![image](https://user-images.githubusercontent.com/15526875/60379541-77ed9780-99e9-11e9-9d6a-a981244b0ac2.png)

**Describe the bug**
There is a rail inside the depot that allows you to place signals on it.

**Steps to reproduce**
Hover over the depot with a signal and click when a green dot appears.

**Build version**
0.71 2019-06-26 Itch Pre-Alpha

**Platform**
Windows 10 1809

**Reproducibility**
Every time

**Comment by voxeltycoon** [comment]
Fixed in 0.72
