### ISSUE TITLE
You need money for buldoz rail buffer stop

### ISSUE THREAD

**Issue by aLegoz** [voxeltycoon/bug-tracker#7]
You need money for buldoz rail buffer stop.
![](https://i.imgur.com/rO2wkan.png)

**Comment by katepolak** [comment]
I can't replicate that myself, bulldozing it actually gives me money.

**Comment by katepolak** [comment]
Managed to replicate the issue but will open a separate issue for it as it's more than just the buffer stops.

**Comment by andrewpey** [comment]
Fixed in 0.56.
