### ISSUE TITLE
Reconfigure old truck to new one will not leave the old cargo settings

### ISSUE THREAD

**Issue by regstar** [voxeltycoon/bug-tracker#70]
**Describe the bug**
If you want to change an old truck to a new one and send him to the depot, and click wants to reconfigure this truck, old settings for goods will be overwritten. I think he will use the settings if you use something else in the past. E.g. you want to change a coal truck, but you bought another one with iron, the reconfigured truck will use the iron one.

**Steps to reproduce**
- Send truck back to the depot
- Click on reconfigure and choose another truck
- If you buy this truck on the past with the exact same good, it will be correct
- if you bought this truck with another good, it will overwrite the old good

**Build version**
0.71

**Platform**
Windows 10

**Reproducibility**
Every time

**Comment by anthonycl** [comment]
Close the train window and re-open it. Does that fix it? If it does, this needs to be an update to the train UI window the devs need to force close and re-open after an applied change or just update the UI.

**Comment by katepolak** [comment]
The wording is pretty confusing so i am not sure if I understand the exact issue.

If the issue is that the UI says something else than what the track actually caries than it's probably related to #76, #41 and #117.
If the issue is something else than I honestly have no idea what you means.

**Comment by regstar** [comment]
I will check this again and write it better down.

**Comment by regstar** [comment]
Here we go.

1. I bought a truck to load iron ore
![Anmerkung 2019-07-19 191134](https://user-images.githubusercontent.com/16978972/61552888-510b0a00-aa59-11e9-8f2d-f95b995eb6cf.png)

2. After this I send an existing truck to the depot, to upgrade this one. My truck has loaded stone.
![Anmerkung 2019-07-19 191201](https://user-images.githubusercontent.com/16978972/61552922-6ed86f00-aa59-11e9-8214-04cc335a6047.png)

3. After I reconfigure my truck (stone was configured), he will use the iron bar instead of stone (last cargo because I bought this truck to load iron bar).
![Anmerkung 2019-07-19 191252](https://user-images.githubusercontent.com/16978972/61552990-96c7d280-aa59-11e9-9175-2b25fcba0fbd.png)

On my perspective, I expect that my reconfigured truck gets the old cargo setting (stone) instead of the last cargo setting (from my bought truck, iron bar). Hopefully, this explanation is better.

**Comment by andrewpey** [comment]
Fixed.
