### ISSUE TITLE
No scroll list in schedule list

### ISSUE THREAD

**Issue by victorleblais** [voxeltycoon/bug-tracker#71]
**Describe the bug**
There is no scroll list in the schedule list, which makes it go off-screen. The main issue is that it's impossible to remove a vehicle from a line since the "Individual Orders" is at the top of the list.
![image](https://user-images.githubusercontent.com/4365075/60387714-b0ec4180-9aa7-11e9-8f20-419ed4a64a2a.png)

**Steps to reproduce**
Just have a lot of lines.

**Build version**
0.71 2019-06-26 ITCH PRE-ALPHA

**Platform**
Windows 10 Pro N 64bit

**Reproducibility**
100% Reproduction rate.

**Comment by andrewpey** [comment]
Fixed in 0.73.
