### ISSUE TITLE
Highlighting businesses in unowned areas

### ISSUE THREAD

**Issue by juffanoodle** [voxeltycoon/bug-tracker#85]
**Describe the bug**
If there is a town on the border of an area you own, but the town's area itself is not owned, you can highlight the business with a terminal and see the profit %age. May also be able to deliver to it? (untested)

**Steps to reproduce**
Requires a town in an un-owned area, on the border of your owned areas. Map seed for this game is pr1y0r184f , town is Coronado. The town had a iron parts business right on the border.

* Select terminal
* Hover the terminal placement within range of the business in the unowned area.
It will highlight the business and give you a profit margin.

**Build version**
0.71 2019-06-26 ITCH PRE-ALPHA

**Platform**
Windows 10 Pro

**Reproducibility**
Always - as long as geographic preconditions are met.

![image](https://user-images.githubusercontent.com/20750281/60397587-1ceea880-9b81-11e9-8683-537950745c4b.png)

**Comment by katepolak** [comment]
Please use the bug report template, there is a reason it was made.

**Comment by juffanoodle** [comment]
Sorry @polak-jan, I managed to miss the templates and it just sent me to a blank bug report window. Edited. :)

**Comment by andrewpey** [comment]
Fixed in [0.84](https://voxeltycoon.xyz/changelog#0.84).
