### ISSUE TITLE
Move conveyor connector on the same tab like conveyor 

### ISSUE THREAD

**Issue by regstar** [voxeltycoon/bug-tracker#86]
**Is your feature request related to a problem? Please describe.**
It's a bit weird where I can find the conveyor connector.

**Describe the solution you'd like**
It should be better to move the conveyor connector out of the warehouse tab and place it into the conveyor tab.

**Comment by regstar** [comment]
Nice work! Done with the last patch version 0.72.

**Comment by katepolak** [comment]
Thanks for closing, I wasn't sure if it actually fixed this issues so I left it open.
