### ISSUE TITLE
Impossible to remove signals on truss bridges

### ISSUE THREAD

**Issue by victorleblais** [voxeltycoon/bug-tracker#87]
**Describe the bug**
If you place a signal "inside" the truss bridge, you can't remove it without removing the entire bridge.

**Steps to reproduce**
Place a signal on a truss bridge.

This signal can be removed:
![image](https://user-images.githubusercontent.com/4365075/60401875-f08a5a80-9b87-11e9-8ed4-fbb12945e173.png)

Those can't (it removes the entire bridge):
![image](https://user-images.githubusercontent.com/4365075/60401879-fd0eb300-9b87-11e9-8623-3c552c75e76c.png)

**Build version**
0.71 2019-06-26 ITCH PRE-ALPHA

**Platform**
Windows 10 Pro N

**Reproducibility**
100% if you place it inside (see screenshots above)

**Comment by andrewpey** [comment]
Fixed in 0.73.
