### ISSUE TITLE
Inverted scroll with mouse wheel on scrollable text

### ISSUE THREAD

**Issue by lostwizard** [voxeltycoon/bug-tracker#88]
Scrolling text (or other scrollable UI elements) with the mouse wheel goes in the wrong direction. When moving the wheel forward (away from the user), text hidden above the top of the viewport should come into view and when movng the wheel back (toward the user), text hidden below the bottom of the viewport should appear. Instead, it moves in the opposite direction. You can see it on the video settings page without starting a game.

This occurs on Linux (Linux Mint 19.1 but it's unlikely to be distribution or version specific) with build version 0.71. I don't have other systems to test it on. Maybe related to [https://github.com/voxeltycoon/bug-tracker/issues/6](https://github.com/voxeltycoon/bug-tracker/issues/6) but in case it isn't, I though I would report it. (At the very least, it suggests the workaround mentioned on the other issue is incomplete.)

**Comment by katepolak** [comment]
That's quite weird, I am not sure Devs updated to the version of Unity yet to is really seems to be a bug in the workaround. Probably that it doesn't detect a Linux system properly.

**Comment by the-moonwitch** [comment]
Happening on Arch as well.

**Comment by katepolak** [comment]
Plase use the bug report template fo your future reports.

**Comment by victorleblais** [comment]
Isn't that a setting that should somehow depend on the OS setting?

I don't know for various Linux distributions, but in OSX you can choose "Natural scrolling" vs "Regular scrolling".

"Natural scrolling" is similar to how it works on touchscreens: scrolling up moves the content upwards and thus reveals content at the bottom. It feels like you're "physically" dragging the content.
That's apparently the behavior you have.

"Regular scrolling" is how scroll wheels "historically worked": scrolling up moves the content downwards to reval content at the top, which to me is the "natural way" to scroll :p

**Comment by lostwizard** [comment]
polak-jan: apologies. Operator error apparently resulted in the template disappearing when I started typing so I didn't notice it was there.

victorleblais: You would think it would be an OS level setting. However, I'm not aware of any setting on Linux desktops that swaps scrolling direction with the mouse wheel. There definitely isn't one on my Linux Mint MATE installation. I suspect the "touch and drag" input on a touch screen and the mouse scroll wheel are distinct inputs and something fairly high up in the GUI stack figures out what to do with them (Say Gtk, Qt, Unity, etc.).

**Comment by hasezoey** [comment]
can confirm that the mous scroll is inverted, just bought the game, and wanted to scroll down in the settings menu
- Linux Mint 19.1
- Kernel 5.0.21
- DE: Cinnamon (4.0.10)

**Comment by andrewpey** [comment]
Does this apply to the in-game camera zooming as well or just UI elements?

**Comment by andrewpey** [comment]
No additional info was provided, closing.
