### ISSUE TITLE
Can not select german locale

### ISSUE THREAD

**Issue by messias72** [voxeltycoon/bug-tracker#89]
**Describe the bug**
In game under settings -> game
There are no german language. In Content\base\localization are the files present.

**Steps to reproduce**
Start game -> settings -> game

**Build version**
0.71 2019-06-26

**Platform**
Windows

**Reproducibility**
every time

**Comment by messias72** [comment]
set in de.locale hidden to false

**Comment by katepolak** [comment]
This is not a bug but a feature, the locale is intentionally hidden as it isn't finished. Closing
